variable "bastion_config" {}
variable "bastion_image" {}
variable "env" {}
variable "index" {}
variable "nat_image" {}
variable "project" {}
variable "worker_account_json_com" {}
variable "worker_account_json_org" {}
variable "worker_chef_json_com" {}
variable "worker_chef_json_org" {}
variable "worker_config_com" {}
variable "worker_config_org" {}
variable "worker_image" {}
