#!/usr/bin/env bash
# vim:filetype=sh
set -o errexit

main() {
  local job="${1}"
  local out="${2}"

  : "${ETC_DEFAULT:=/etc/default}"

  if [[ "${out}" ]]; then
    echo "${out}"
    exec 1>"${out}"
  fi

  for config_file in \
    travis-enterprise \
    "${job}-chef" \
    "${job}" \
    "${job}-cloud-init" \
    "${job}-local"; do
    if [ -f "${ETC_DEFAULT}/${config_file}" ]; then
      echo "# ${ETC_DEFAULT}/${config_file}"
      sed "s/^export //;s/\"//g;s/'//g" "${ETC_DEFAULT}/${config_file}"
    fi
  done
}

main "$@"
