variable "index" {}
variable "vanilla_image" {}
variable "datacenter" {}
variable "cluster" {}
variable "datastore" {}
variable "internal_network_label" {}
variable "management_network_label" {}
variable "jobs_network_label" {}
variable "wjb_num" {}
variable "threatstack_key" {}
variable "ssh_user" {}
