AMQP_URL_COM_VARNAME := CLOUDAMQP_URL
AMQP_URL_ORG_VARNAME := CLOUDAMQP_GRAY_URL
GCE_PROJECT := travis-ci-prod-2
GKE_CLUSTER_NAME := gce-production-2
GKE_CLUSTER_ZONE := us-central1

include $(shell git rev-parse --show-toplevel)/gce.mk
