AMQP_URL_COM_VARNAME := CLOUDAMQP_URL
AMQP_URL_ORG_VARNAME := CLOUDAMQP_GRAY_URL

include $(shell git rev-parse --show-toplevel)/gce.mk

plan:
	@echo DISABLED OK

apply:
	@echo NO REALLY DONT DO THIS
