AMQP_URL_COM_VARNAME := CLOUDAMQP_URL
AMQP_URL_ORG_VARNAME := CLOUDAMQP_GRAY_URL
GCE_PROJECT := eco-emissary-99515
GKE_CLUSTER_NAME := gce-production-1
GKE_CLUSTER_ZONE := us-central1-a

include $(shell git rev-parse --show-toplevel)/gce.mk
