variable "index" {}
variable "vanilla_image" {}
variable "datacenter" {}
variable "cluster" {}
variable "datastore" {}
variable "internal_network_label" {}
variable "management_network_label" {}
variable "jobs_network_label" {}
variable "jobs_network_subnet" {}
variable "threatstack_key" {}
variable "travisci_net_external_zone_id" {}
variable "vsphere_ip" {}
variable "ssh_user" {}
variable "vm_ssh_key_path" {}
variable "custom_1_name" {}
variable "custom_2_name" {}
variable "custom_4_name" {}
variable "custom_5_name" {}
variable "custom_6_name" {}
