TRAVIS_BUILD_COM_HOST := build-staging.travis-ci.com
TRAVIS_BUILD_ORG_HOST := build-staging.travis-ci.org
JOB_BOARD_HOST := job-board-staging.travis-ci.com
AMQP_URL_VARNAME := CLOUDAMQP_URL

include $(shell git rev-parse --show-toplevel)/aws.mk

plan:
	@echo NO

apply:
	@echo STILL NO
