variable "az" {}
variable "bastion_ami" {}
variable "bastion_config" {}
variable "env" {}
variable "gateway_id" {}
variable "nat_ami" {}
variable "nat_instance_type" {}
variable "public_subnet" {}
variable "vpc_id" {}
variable "workers_com_subnet" {}
variable "workers_org_subnet" {}
