#!/usr/bin/env bash
set -o errexit

main() {
  [[ "${QUIET}" ]] || set -o xtrace

  : "${SQUIGNIX_IMAGE:=tianon/squignix}"

  local name=squignix
  if [[ "${1}" ]]; then
    name="${1}"
  fi

  local env_file
  env_file="$(tfw writeenv squignix)"

  set -o allexport
  # shellcheck source=/dev/null
  source "${env_file}"

  mkdir -p /var/tmp/nginx-cache
  exec docker run \
    --rm \
    --name "${name}" \
    -p 80:80 \
    -v /var/tmp/nginx-conf.d:/etc/nginx/conf.d \
    -v /var/tmp/nginx-cache:/var/cache/nginx \
    "${SQUIGNIX_IMAGE}"
}

main "${@}"
